/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 3dProperty.gltf --transform
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

function Model(props) {
  const { nodes, materials } = useGLTF('/3dProperty-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.cornice_ws.geometry}
        material={materials.PaletteMaterial001}
        position={[1.01, 0, -0.617]}
        rotation={[0, -0.096, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes['Bed_49-40_001'].geometry}
        material={materials['Bed_49-40_sheet.002']}
        position={[-0.316, 0, 1.144]}
        rotation={[-Math.PI, 0.008, -Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Courain_122.geometry}
        material={materials['curtains.003']}
        position={[2.199, 1.254, 0.799]}
        rotation={[-Math.PI / 2, 0, 1.564]}
        scale={[-0.015, -0.004, -0.01]}
      />
      <group
        position={[1.56, 0, 1.052]}
        rotation={[-Math.PI, 0.008, -Math.PI]}
        scale={0.01}>
        <mesh
          geometry={nodes.Mesh518.geometry}
          material={materials['Sofa_48-02_wood.002']}
        />
        <mesh
          geometry={nodes.Mesh518_1.geometry}
          material={materials['Sofa_48-02_fabric.002']}
        />
        <mesh
          geometry={nodes.Mesh518_2.geometry}
          material={materials['Sofa_48-02_pillows.002']}
        />
      </group>
      <group
        position={[1.093, 0, -1.478]}
        rotation={[0, -0.008, 0]}
        scale={0.01}>
        <mesh
          geometry={nodes.Mesh519.geometry}
          material={materials['net_panel.007']}
        />
        <mesh
          geometry={nodes.Mesh519_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        geometry={nodes['Table_Coffee_97-31_001'].geometry}
        material={materials['Table_Coffee_97-31_wood.002']}
        position={[1.67, 0, -0.017]}
        rotation={[Math.PI, -1.388, Math.PI]}
        scale={0.01}
      />
      <group
        position={[-0.354, 1.368, -2.491]}
        rotation={[0, -0.001, 0]}
        scale={0.01}>
        <mesh
          geometry={nodes.Mesh521.geometry}
          material={materials['Wall_Pictures_37-46_photo01.002']}
        />
        <mesh
          geometry={nodes.Mesh521_1.geometry}
          material={materials['Wall_Pictures_37-46_photo02.002']}
        />
        <mesh
          geometry={nodes.Mesh521_2.geometry}
          material={materials['Wall_Pictures_37-46_photo03.002']}
        />
        <mesh
          geometry={nodes.Mesh521_3.geometry}
          material={materials['Wall_Pictures_37-46_photo04.002']}
        />
      </group>
      <group position={[1.366, 1.727, -2.502]} scale={0.01}>
        <mesh
          geometry={nodes.Mesh522.geometry}
          material={materials['Image_01.007']}
        />
        <mesh
          geometry={nodes.Mesh522_1.geometry}
          material={materials['Image_02.007']}
        />
        <mesh
          geometry={nodes.Mesh522_2.geometry}
          material={materials['Image_03.007']}
        />
        <mesh
          geometry={nodes.Mesh522_3.geometry}
          material={materials['Image_04.007']}
        />
        <mesh
          geometry={nodes.Mesh522_4.geometry}
          material={materials['Chipboard.007']}
        />
      </group>
      <group
        position={[-0.083, 0, -1.51]}
        rotation={[Math.PI, -0.079, Math.PI]}
        scale={0.01}>
        <mesh
          geometry={nodes.Mesh523.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          geometry={nodes.Mesh523_1.geometry}
          material={materials['Chair_022_legs.002']}
        />
      </group>
      <group
        position={[-0.349, 0.75, -2.385]}
        rotation={[0, 0.079, 0]}
        scale={0.01}>
        <mesh
          geometry={nodes.Mesh524.geometry}
          material={materials['Stationery_Box_markers.002']}
        />
        <mesh
          geometry={nodes.Mesh524_1.geometry}
          material={materials['Stationery_Box_wood.002']}
        />
      </group>
      <group
        position={[-0.633, 0.75, -2.335]}
        rotation={[0, -0.008, 0]}
        scale={0.01}>
        <mesh
          geometry={nodes.Mesh525.geometry}
          material={materials['Pencil_02.002']}
        />
        <mesh
          geometry={nodes.Mesh525_1.geometry}
          material={materials['paper.002']}
        />
        <mesh
          geometry={nodes.Mesh525_2.geometry}
          material={materials['tape02.002']}
        />
        <mesh
          geometry={nodes.Mesh525_3.geometry}
          material={materials['wood_toolbox.002']}
        />
      </group>
      <mesh
        geometry={nodes.Breakfast_Meal_Coffee_29_15_002.geometry}
        material={materials['Breakfast_Meal_Coffee_29_15_coffee.002']}
        position={[-0.463, 0.75, -2.069]}
        rotation={[0, -0.968, 0]}
        scale={0.01}
      />
      <group
        position={[3.593, 0, -0.583]}
        rotation={[0, 0.952, 0]}
        scale={0.01}>
        <mesh
          geometry={nodes.Mesh527.geometry}
          material={materials['Chair_Lounge_48-31_wood.002']}
        />
        <mesh
          geometry={nodes.Mesh527_1.geometry}
          material={materials['Chair_Lounge_48-31_fabric.002']}
        />
      </group>
      <mesh
        geometry={nodes['Wall_Pictures_83-20_001'].geometry}
        material={materials['Wall_Pictures_83-20_images.002']}
        position={[-0.298, 1.26, 2.255]}
        rotation={[Math.PI, -0.002, Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Print_Art_003_001.geometry}
        material={materials['printArt03_picture.002']}
        position={[-0.973, 1.649, 0.942]}
        rotation={[-Math.PI, 1.569, -Math.PI]}
        scale={0.007}
      />
      <mesh
        geometry={nodes['Cabinet_Bedside_49-10_001'].geometry}
        material={materials['Cabinet_Bedside_49-10_wood.002']}
        position={[0.482, 0, 2.016]}
        rotation={[-Math.PI, 0.001, -Math.PI]}
        scale={0.01}
        castShadow
      />
      <group
        position={[0.579, 0.63, 2.137]}
        rotation={[Math.PI, -0.428, Math.PI]}
        scale={0.01}>
        <mesh
          geometry={nodes.Mesh531.geometry}
          material={materials['tablePicture_frame.003']}
        />
        <mesh
          geometry={nodes.Mesh531_1.geometry}
          material={materials['tablePicture_picture.003']}
        />
      </group>
      <mesh
        geometry={nodes.kling_ral_9003_cream.geometry}
        material={materials['stucco.007']}
        position={[3.693, -0.137, 0.03]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Tiles.geometry}
        material={materials['Tiles - WC - Floor - Grey.003']}
        position={[-2.411, 1.148, 0.97]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.wood___slats___vertical.geometry}
        material={materials['wood_terase.003']}
        position={[3.693, 0, 0.03]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.siding___light.geometry}
        material={materials['wood-28.007']}
        position={[-0.736, 0, -0.005]}
        scale={0.01}
        receiveShadow
      />
      <mesh
        geometry={nodes.wood___pine_grained_vertical.geometry}
        material={materials.furniture_wood}
        position={[0.681, 1.216, -0.328]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.frontdoorwall.geometry}
        material={materials.PaletteMaterial004}
        position={[-28.25, -2.865, -11.308]}
        rotation={[0, -0.096, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload('/3dProperty-transformed.glb');

export default Model;
